using BNLReloadedServer.BaseTypes;
using BNLReloadedServer.ServerTypes;
using BNLReloadedServer.Service;
using Moserware.Skills;

namespace BNLReloadedServer.Database;

public interface IRegionServerDatabase
{
    public bool UserConnected(uint userId);
    public void UserUiChanged(uint userId, UiId uiId, float duration);
    public UiId? GetUiId(uint userId);
    public bool UpdateScene(uint userId, Scene scene, IServiceScene sceneService, bool enterInstance);
    public bool UpdateScene(uint userId, Scene scene, bool forceEnterInstance = false);
    public void UserEnterScene(uint userId);
    public Scene GetLastScene(uint userId);
    public bool RegisterService(Guid sessionId, IService service, ServiceId serviceId);
    public bool RegisterMatchService(Guid sessionId, IService service, ServiceId serviceId);
    public void RemoveServices(Guid sessionId);
    public void RemoveMatchServices(Guid sessionId);
    public bool LinkMatchSessionGuidToUser(uint userId, Guid sessionId);
    public bool AddUser(uint userId, Guid sessionId);
    public bool RemoveUser(uint userId, Guid? sessionId = null);
    public bool UpdateChatName(uint userId, string newName);
    public Task NotifyFriends(uint playerId);
    public Task NotifyRequests(uint playerId, bool requestsForMe, bool requestsFromMe);
    public void NotifyLeague(uint playerId, League league);
    public List<CustomGameInfo> GetCustomGames();
    public ulong? AddCustomGame(string name, string password, uint playerId);
    public bool RemoveCustomGame(ulong gameId);
    public CustomGameJoinResult AddToCustomGame(uint playerId, ulong gameId, string password);
    public bool BackfillCustomGame(uint playerId);
    public CustomGameSpectateResult CheckSpectateCustomGame(uint playerId, ulong gameId, string password);
    public bool SpectateCustomGame(uint playerId, ulong gameId);
    public bool RemoveFromCustomGame(uint playerId);
    public bool KickFromCustomGame(uint playerId, uint kickerId);
    public bool SwitchTeam(uint playerId);
    public bool UpdateCustomSettings(uint playerId, CustomGameSettings settings);
    public CustomGameUpdate? GetFullCustomGameUpdate(uint playerId);
    public bool StartCustomGame(uint playerId, string? signedMap);
    public bool StartMapEditorGame(uint playerId, MapData map, Key heroKey, TeamType team);
    public bool StartTimeTrialGame(uint playerId);
    public bool RestartTimeTrialGame(uint playerId);
    public bool StartGameFromMatchmaker(CardGameMode gameMode, List<PlayerQueueData> team1, List<PlayerQueueData> team2);
    public bool BackfillMatchmakerGame(PlayerQueueData player, TeamType team, string gameInstanceId);
    public bool SetIgnored(uint playerId, uint targetId, bool ignore);
    public void SendIgnoresTo(uint playerId);
    public bool SendMessage(uint playerId, RoomId roomId, string message);
    public PrivateMessageFailReason? SendMessage(uint playerId, uint receiver, string message);
    public IGameInstance? GetGameInstance(uint? playerId);
    public bool RemoveGameInstance(string gameInstanceId);
    public bool RemoveFromGameInstance(uint playerId, string gameInstanceId);
    public IEnumerable<(Dictionary<uint, Rating> team1, Dictionary<uint, Rating> team2, string instanceId)> GetBackfillNeeded(Key gameModeKey);
    public int GetActiveGamesCount(Key gameModeKey);
    public List<QueueSnapshot> GetQueueSnapshot();
    public PlayerActivity GetPlayerActivity();
    public void JoinQueue(uint playerId, Key gameModeKey, IServiceMatchmaker serviceMatchmaker);
    public void LeaveQueue(uint playerId, IServiceMatchmaker serviceMatchmaker);
    public void EnableBackfilling(uint playerId, bool enable);
    public void ConfirmMatch(uint playerId, bool confirm, IServiceMatchmaker serviceMatchmaker);
    public void ForceStartMatch(uint playerId);
    public ulong? CreateSquad(uint ownerId, List<uint> players);
    public bool JoinSquad(uint playerId, ulong squadId);
    public bool LeaveSquad(uint playerId);
    public bool KickFromSquad(uint playerId, uint kickerId);
    public bool SendSquadInvite(uint playerId, uint senderId, Key gameModeKey);
    public bool SendSquadInviteReply(uint playerId, uint senderId, SquadInviteReplyType reply);
    public bool SetSquadGamemode(uint playerId, Key gameModeKey);
    public bool ClearSquadId(uint playerId, ulong squadId);
    public Guid? GetSessionGuid(uint playerId);
    public IServicePlayer? GetPlayerService(uint playerId);
    public IServiceChat? GetChatService(uint playerId);
    public bool SchedulePlayerNotification(uint playerId, string message);
    public int BroadcastPlayerNotification(string message);
    public bool MatchmakingEnabled { get; }
    public void SetMatchmakingEnabled(bool enabled);
    public void CloseSquad(ulong squadId);
    public ulong? GetSquadId(uint playerId);
    public bool IsSquadLeader(uint playerId);
    public void SendAfkWarning(uint playerId, string gameInstanceId);
    public void KickForAfk(uint playerId, string gameInstanceId);
    public void FreeMatchmakerSlot(uint playerId, string gameInstanceId);
    public bool IsUserOnline(uint playerId);
    public void RemoveOfflineUser(uint playerId);
}
