using System.Collections.Concurrent;
using System.Diagnostics;
using System.Net;
using System.Security.Cryptography;
using System.Text.Json;
using BNLReloadedServer.BaseTypes;
using BNLReloadedServer.Database;
using BNLReloadedServer.Logging;
using BNLReloadedServer.ProtocolHelpers;
using BNLReloadedServer.Servers;
namespace BNLReloadedServer.ControlPanel;

public sealed class ControlPanelServer : IDisposable
{
    private const string SessionCookieName = "cp_session";
    private static readonly TimeSpan SessionDuration = TimeSpan.FromHours(12);
    private const int MaxFailedAttempts = 5;
    private static readonly TimeSpan LockoutWindow = TimeSpan.FromMinutes(15);

    private readonly HttpListener _listener;
    private readonly CancellationTokenSource _cts = new();
    private readonly MasterServer? _masterServer;
    private readonly RegionServer _regionServer;
    private readonly MatchServer _matchServer;
    private readonly CouchCatalogueStore _catalogueStore;
    private readonly ServerCatalogue _serverCatalogue;
    private readonly DateTime _startTime = DateTime.UtcNow;
    private readonly ConcurrentDictionary<string, DateTime> _sessions = new();
    private readonly ConcurrentDictionary<string, (int Count, DateTime WindowStart)> _failedAttempts = new();
    private Task? _listenTask;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
    };

    public ControlPanelServer(
        string prefix,
        MasterServer? masterServer,
        RegionServer regionServer,
        MatchServer matchServer,
        CouchCatalogueStore catalogueStore,
        ServerCatalogue serverCatalogue)
    {
        _listener = new HttpListener();
        _listener.Prefixes.Add(prefix);
        _masterServer = masterServer;
        _regionServer = regionServer;
        _matchServer = matchServer;
        _catalogueStore = catalogueStore;
        _serverCatalogue = serverCatalogue;
    }

    public void Start()
    {
        if (string.IsNullOrEmpty(Databases.ConfigDatabase.ControlPanelPasswordHash()))
        {
            Log.Warn(LogCat.Panel, "No control_panel_password_hash configured, refusing to start (would be unauthenticated).");
            return;
        }

        try
        {
            _listener.Start();
            _listenTask = Task.Run(() => ListenLoop(_cts.Token));
            Log.Info(LogCat.Panel, $"Listening on {string.Join(", ", _listener.Prefixes)}");
        }
        catch (Exception ex)
        {
            Log.Error(LogCat.Panel, "Failed to start", ex);
        }
    }

    public void Stop()
    {
        _cts.Cancel();
        try
        {
            _listener.Stop();
        }
        catch
        {
        }
    }

    public void Dispose()
    {
        Stop();
        _cts.Dispose();
        ((IDisposable)_listener).Dispose();
    }

    private async Task ListenLoop(CancellationToken ct)
    {
        while (!ct.IsCancellationRequested)
        {
            try
            {
                var ctx = await _listener.GetContextAsync().WaitAsync(ct);
                _ = HandleRequestAsync(ctx);
            }
            catch (OperationCanceledException)
            {
                break;
            }
            catch (HttpListenerException) when (ct.IsCancellationRequested)
            {
                break;
            }
            catch (Exception ex)
            {
                Log.Error(LogCat.Panel, "Request failed", ex);
            }
        }
    }

    private async Task HandleRequestAsync(HttpListenerContext ctx)
    {
        try
        {
            var path = ctx.Request.Url?.AbsolutePath ?? "/";
            var method = ctx.Request.HttpMethod;

            if (method == "GET" && path == "/")
            {
                await ServeFile(ctx, "index.html", "text/html; charset=utf-8");
                return;
            }

            if (method == "GET" && path == "/style.css")
            {
                await ServeFile(ctx, "style.css", "text/css; charset=utf-8");
                return;
            }

            if (method == "GET" && path == "/app.js")
            {
                await ServeFile(ctx, "app.js", "application/javascript; charset=utf-8");
                return;
            }

            // Which sprites the panel actually ships, generated by sprites.py.
            if (method == "GET" && path == "/sprites.js")
            {
                await ServeFile(ctx, "sprites.js", "application/javascript; charset=utf-8");
                return;
            }

            // The panel's art. Unauthenticated like the three files above it, because the
            // login gate shows the logo. ServeFile cannot be used: it re-encodes as UTF-8,
            // which corrupts anything that isn't text.
            if (method == "GET" && path.StartsWith("/assets/"))
            {
                await ServeAsset(ctx, path["/assets/".Length..]);
                return;
            }

            if (method == "POST" && path == "/api/login")
            {
                await HandleLogin(ctx);
                return;
            }

            if (method == "POST" && path == "/api/logout")
            {
                HandleLogout(ctx);
                await WriteJson(ctx, new { message = "OK" });
                return;
            }

            if (method == "GET" && path == "/api/public/status")
            {
                await ServePublicStatus(ctx);
                return;
            }

            if (!IsAuthenticated(ctx))
            {
                ctx.Response.StatusCode = 401;
                await WriteJson(ctx, new { error = "Unauthorized" });
                return;
            }

            if (method == "GET" && path == "/api/status")
            {
                await ServeStatus(ctx);
                return;
            }

            if (method == "POST" && path == "/api/refreshCdbLoad")
            {
                await ExecuteAction(ctx, RefreshCatalogue);
                return;
            }

            if (method == "POST" && path == "/api/reset")
            {
                await ServeReset(ctx);
                return;
            }

            if (method == "GET" && path == "/api/queues")
            {
                await ServeQueues(ctx);
                return;
            }

            if (method == "GET" && path == "/api/activity")
            {
                await ServeActivity(ctx);
                return;
            }

            if (method == "GET" && path == "/api/matches")
            {
                await ServeMatchHistory(ctx);
                return;
            }

            if (method == "GET" && path.StartsWith("/api/matches/"))
            {
                await ServeMatchDetail(ctx, Uri.UnescapeDataString(path["/api/matches/".Length..]));
                return;
            }

            if (method == "GET" && path == "/api/players")
            {
                await ServePlayerList(ctx);
                return;
            }

            if (path.StartsWith("/api/players/") && uint.TryParse(path["/api/players/".Length..], out var playerId))
            {
                if (method == "GET")
                {
                    await ServePlayerDetail(ctx, playerId);
                    return;
                }
                if (method == "POST")
                {
                    await HandlePlayerUpdate(ctx, playerId);
                    return;
                }
            }

            if (method == "GET" && path.StartsWith("/api/cards/"))
            {
                await ServeCard(ctx, Uri.UnescapeDataString(path["/api/cards/".Length..]));
                return;
            }

            if (method == "GET" && path == "/api/maps")
            {
                await ServeMaps(ctx);
                return;
            }

            if (method == "GET" && path.StartsWith("/api/maps/") && path.EndsWith("/download"))
            {
                var key = Uri.UnescapeDataString(path["/api/maps/".Length..^"/download".Length]);
                await ServeMapDownload(ctx, key);
                return;
            }

            if (method == "POST" && path.StartsWith("/api/map-pools/"))
            {
                await HandleMapPoolUpdate(ctx, path["/api/map-pools/".Length..]);
                return;
            }

            if (method == "GET" && path == "/api/logs")
            {
                await ServeLogs(ctx, ctx.Request.QueryString["since"]);
                return;
            }

            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Not found" });
        }
        catch (Exception ex)
        {
            ctx.Response.StatusCode = 500;
            await WriteJson(ctx, new { error = ex.Message });
        }
    }

    private static object DescribeArchiveKey(long hash)
    {
        var card = Databases.Catalogue.All.FirstOrDefault(card => card.Key.Hash == (uint)hash);
        return new
        {
            key = card?.Id ?? hash.ToString(),
            name = card switch
            {
                CardMap map => map.Name?.Text ?? map.Id,
                CardUnit unit => unit.Name?.Text ?? unit.Id,
                CardDevice device => device.Name?.Text ?? device.Id,
                CardPerk perk => perk.Name?.Text ?? perk.Id,
                CardSkin skin => skin.Name?.Text ?? skin.Id,
                CardGameMode mode => mode.Name ?? mode.Id,
                _ => card?.Id ?? hash.ToString()
            }
        };
    }

    private async Task ServeMatchHistory(HttpListenerContext ctx)
    {
        var limit = int.TryParse(ctx.Request.QueryString["limit"], out var requested) ? requested : 50;
        long? before = long.TryParse(ctx.Request.QueryString["before"], out var cursor) ? cursor : null;
        var matches = await Databases.MasterServerDatabase.GetCompletedMatches(limit, before);
        await WriteJson(ctx, new
        {
            items = matches.Select(match => new
            {
                id = match.Id,
                map = DescribeArchiveKey(match.MapKey),
                mode = DescribeArchiveKey(match.GameModeKey),
                started_at = match.StartedAt,
                ended_at = match.EndedAt,
                duration_seconds = Math.Max(0, match.EndedAt - match.StartedAt) / 1000,
                winner = ((TeamType)match.Winner).ToString()
            }),
            next_before = matches.Count == Math.Clamp(limit, 1, 100) ? matches[^1].EndedAt : (long?)null
        });
    }

    private async Task ServeMatchDetail(HttpListenerContext ctx, string matchId)
    {
        var detail = await Databases.MasterServerDatabase.GetCompletedMatch(matchId);
        if (detail == null)
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Match not found" });
            return;
        }

        Dictionary<PlayerMatchStatType, int> ReadStats(byte[] bytes)
        {
            using var stream = new MemoryStream(bytes);
            using var reader = new BinaryReader(stream);
            return reader.ReadMap<PlayerMatchStatType, int, Dictionary<PlayerMatchStatType, int>>(
                reader.ReadByteEnum<PlayerMatchStatType>, reader.ReadInt32);
        }

        var presencesByPlayer = detail.Presences.GroupBy(row => row.PlayerId)
            .ToDictionary(group => group.Key, group => group.OrderBy(row => row.Sequence).ToList());
        await WriteJson(ctx, new
        {
            id = detail.Match.Id,
            map = DescribeArchiveKey(detail.Match.MapKey),
            mode = DescribeArchiveKey(detail.Match.GameModeKey),
            started_at = detail.Match.StartedAt,
            ended_at = detail.Match.EndedAt,
            winner = ((TeamType)detail.Match.Winner).ToString(),
            teams = detail.Teams.Select(team => new
            {
                team = ((TeamType)team.Team).ToString(),
                is_winner = team.IsWinner,
                cubes_at_start = team.CubesAtStart,
                cubes_remaining = team.CubesRemaining,
                cubes_destroyed = team.CubesAtStart - team.CubesRemaining,
                base_destroyed = team.BaseDestroyed
            }),
            players = detail.Players.Select(player => new
            {
                player_id = player.PlayerId,
                nickname = player.Nickname,
                squad_id = player.SquadId,
                was_initial = player.WasInitial,
                was_backfiller = player.WasBackfiller,
                is_winner = player.IsWinner,
                total_score = player.TotalScore,
                stats = ReadStats(player.Stats).ToDictionary(pair => pair.Key.ToString(), pair => pair.Value),
                presences = presencesByPlayer.GetValueOrDefault(player.PlayerId, []).Select(presence => new
                {
                    sequence = presence.Sequence,
                    joined_at = presence.JoinedAt,
                    left_at = presence.LeftAt,
                    join_kind = ((MatchJoinKind)presence.JoinKind).ToString(),
                    leave_kind = presence.LeaveKind.HasValue ? ((MatchLeaveKind)presence.LeaveKind.Value).ToString() : null,
                    team = ((TeamType)presence.Team).ToString(),
                    hero = DescribeArchiveKey(presence.HeroKey),
                    skin = DescribeArchiveKey(presence.SkinKey),
                    devices = detail.Devices.Where(row => row.PresenceId == presence.Id).OrderBy(row => row.Slot)
                        .Select(row => new { slot = row.Slot, device = DescribeArchiveKey(row.DeviceKey), level = row.DeviceLevel }),
                    perks = detail.Perks.Where(row => row.PresenceId == presence.Id).OrderBy(row => row.Slot)
                        .Select(row => new { slot = row.Slot, perk = DescribeArchiveKey(row.PerkKey) })
                })
            })
        });
    }

    private static string ClientIp(HttpListenerContext ctx)
    {
        var forwarded = ctx.Request.Headers["X-Real-IP"] ?? ctx.Request.Headers["X-Forwarded-For"];
        if (!string.IsNullOrEmpty(forwarded))
            return forwarded.Split(',')[0].Trim();

        return ctx.Request.RemoteEndPoint?.Address.ToString() ?? "unknown";
    }

    private bool IsAuthenticated(HttpListenerContext ctx)
    {
        var cookie = ctx.Request.Cookies[SessionCookieName];
        if (cookie == null || string.IsNullOrEmpty(cookie.Value))
            return false;

        if (!_sessions.TryGetValue(cookie.Value, out var expiry) || expiry <= DateTime.UtcNow)
        {
            _sessions.TryRemove(cookie.Value, out _);
            return false;
        }

        return true;
    }

    private bool IsLockedOut(string ip)
    {
        if (!_failedAttempts.TryGetValue(ip, out var entry))
            return false;

        if (DateTime.UtcNow - entry.WindowStart > LockoutWindow)
        {
            _failedAttempts.TryRemove(ip, out _);
            return false;
        }

        return entry.Count >= MaxFailedAttempts;
    }

    private void RecordFailedAttempt(string ip)
    {
        _failedAttempts.AddOrUpdate(
            ip,
            _ => (1, DateTime.UtcNow),
            (_, entry) => DateTime.UtcNow - entry.WindowStart > LockoutWindow
                ? (1, DateTime.UtcNow)
                : (entry.Count + 1, entry.WindowStart));
    }

    private async Task HandleLogin(HttpListenerContext ctx)
    {
        var ip = ClientIp(ctx);

        if (IsLockedOut(ip))
        {
            Log.Warn(LogCat.Panel, $"Login blocked (too many failed attempts) from {ip}");
            ctx.Response.StatusCode = 429;
            await WriteJson(ctx, new { error = "Too many failed attempts. Try again later." });
            return;
        }

        using var reader = new StreamReader(ctx.Request.InputStream);
        var body = await reader.ReadToEndAsync();

        string? password = null;
        try
        {
            using var doc = JsonDocument.Parse(body);
            if (doc.RootElement.TryGetProperty("password", out var pw))
                password = pw.GetString();
        }
        catch (JsonException)
        {
        }

        var storedHash = Databases.ConfigDatabase.ControlPanelPasswordHash();
        var match = PasswordHasher.Verify(password ?? string.Empty, storedHash);

        if (!match)
        {
            RecordFailedAttempt(ip);
            Log.Warn(LogCat.Panel, $"Failed login attempt from {ip}");
            ctx.Response.StatusCode = 401;
            await WriteJson(ctx, new { error = "Invalid password" });
            return;
        }

        _failedAttempts.TryRemove(ip, out _);

        var token = Convert.ToBase64String(RandomNumberGenerator.GetBytes(32));
        var expiry = DateTime.UtcNow + SessionDuration;
        _sessions[token] = expiry;

        Log.Info(LogCat.Panel, $"Successful login from {ip}");

        ctx.Response.Headers.Add("Set-Cookie",
            $"{SessionCookieName}={token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age={(int)SessionDuration.TotalSeconds}");
        await WriteJson(ctx, new { message = "OK" });
    }

    private void HandleLogout(HttpListenerContext ctx)
    {
        var cookie = ctx.Request.Cookies[SessionCookieName];
        if (cookie != null && !string.IsNullOrEmpty(cookie.Value))
            _sessions.TryRemove(cookie.Value, out _);

        ctx.Response.Headers.Add("Set-Cookie", $"{SessionCookieName}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0");
    }

    private static readonly string ControlPanelFolderPath = Path.Combine(AppContext.BaseDirectory, "ControlPanel");

    private static async Task ServeFile(HttpListenerContext ctx, string fileName, string contentType)
    {
        var content = await File.ReadAllTextAsync(Path.Combine(ControlPanelFolderPath, fileName));

        ctx.Response.ContentType = contentType;
        var buf = System.Text.Encoding.UTF8.GetBytes(content);
        ctx.Response.ContentLength64 = buf.Length;
        await ctx.Response.OutputStream.WriteAsync(buf);
        ctx.Response.OutputStream.Close();
    }

    private static readonly Dictionary<string, string> AssetContentTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        [".png"] = "image/png",
        [".jpg"] = "image/jpeg",
        [".jpeg"] = "image/jpeg",
        [".gif"] = "image/gif",
        [".webp"] = "image/webp",
        [".svg"] = "image/svg+xml",
        [".ico"] = "image/x-icon",
        [".woff2"] = "font/woff2"
    };

    private static async Task ServeAsset(HttpListenerContext ctx, string relativePath)
    {
        var assetsRoot = Path.Combine(ControlPanelFolderPath, "assets");
        var fullPath = Path.GetFullPath(Path.Combine(assetsRoot, Uri.UnescapeDataString(relativePath)));

        // Everything served has to sit under assets/ no matter what the request said.
        if (!fullPath.StartsWith(assetsRoot + Path.DirectorySeparatorChar, StringComparison.Ordinal) ||
            !File.Exists(fullPath) ||
            !AssetContentTypes.TryGetValue(Path.GetExtension(fullPath), out var contentType))
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Not found" });
            return;
        }

        var bytes = await File.ReadAllBytesAsync(fullPath);
        ctx.Response.ContentType = contentType;
        ctx.Response.Headers["Cache-Control"] = "public, max-age=86400";
        ctx.Response.ContentLength64 = bytes.Length;
        await ctx.Response.OutputStream.WriteAsync(bytes);
        ctx.Response.OutputStream.Close();
    }

    private async Task ServeStatus(HttpListenerContext ctx)
    {
        var regions = Databases.MasterServerDatabase.GetRegionServers();
        var totalPlayers = regions.Sum(r => Databases.MasterServerDatabase.GetRegionPlayerCount(r.Id!));

        var status = new
        {
            uptime = (DateTime.UtcNow - _startTime).ToString(@"d\.hh\:mm\:ss"),
            uptime_seconds = (long)(DateTime.UtcNow - _startTime).TotalSeconds,
            is_master = Databases.ConfigDatabase.IsMaster(),
            master_running = _masterServer?.IsStarted ?? false,
            region_running = _regionServer.IsStarted,
            match_running = _matchServer.IsStarted,
            player_count = totalPlayers,
            region_count = regions.Count,
            regions = regions.Select(r => new
            {
                id = r.Id,
                host = r.Host,
                name = r.Info?.Name?.Text,
                players = Databases.MasterServerDatabase.GetRegionPlayerCount(r.Id!)
            })
        };

        await WriteJson(ctx, status);
    }

    /// <remarks>
    /// Deliberately its own route rather than a field on /api/status: the matchmaker is
    /// live state that a reader can find mid-mutation, and a queue that has to report
    /// itself unavailable must not be able to take the status figures with it.
    /// This is <em>this process's</em> region only, while /api/status sums player_count
    /// across every region registered on the master.
    /// </remarks>
    private static async Task ServeQueues(HttpListenerContext ctx)
    {
        // RunServer sets the region database before the panel starts, so in the normal
        // path this holds. It is a settable static with no initializer, though, and a
        // 500 here would say less than an empty list does.
        var queues = Databases.RegionServerDatabase?.GetQueueSnapshot() ?? [];
        await WriteJson(ctx, new { queues });
    }

    /// <remarks>
    /// Region-scoped like /api/queues, and for the same reason kept off /api/status,
    /// whose player_count is summed across every region on the master. The whole
    /// breakdown is counted in one pass server-side so the buckets cannot contradict
    /// each other the way two separately-polled numbers can.
    /// </remarks>
    private static async Task ServeActivity(HttpListenerContext ctx)
    {
        var activity = Databases.RegionServerDatabase?.GetPlayerActivity();
        await WriteJson(ctx, activity ?? new ServerTypes.PlayerActivity(0, 0, []));
    }

    private static async Task ServePublicStatus(HttpListenerContext ctx)
    {
        var playerCount = Databases.MasterServerDatabase.GetRegionServers()
            .Sum(r => Databases.MasterServerDatabase.GetRegionPlayerCount(r.Id!));

        ctx.Response.Headers["Access-Control-Allow-Origin"] = "*";
        ctx.Response.Headers["Cache-Control"] = "no-cache";
        await WriteJson(ctx, new { player_count = playerCount });
    }

    private static async Task ExecuteAction(HttpListenerContext ctx, Action action)
    {
        try
        {
            action();
            await WriteJson(ctx, new { message = "OK" });
        }
        catch (Exception ex)
        {
            ctx.Response.StatusCode = 500;
            await WriteJson(ctx, new { error = ex.Message });
        }
    }

    private static async Task ServeReset(HttpListenerContext ctx)
    {
        Log.Info(LogCat.Panel, "Reset requested, shutting down (expecting the service to relaunch)...");
        await WriteJson(ctx, new { message = "Server is shutting down and should be relaunched by the service shortly." });
        _ = Task.Run(async () =>
        {
            await Task.Delay(300);
            ShutdownSignal.Request();
        });
    }

    private void RefreshCatalogue()
    {
        Log.Info(LogCat.Catalogue, "Refreshing catalogue on control panel request...");
        try
        {
            var newCardList = _catalogueStore.Load();
            _serverCatalogue.Replicate(newCardList);
            var catalogueReplicator = new Service.ServiceCatalogue(new ServerSender(_regionServer));
            catalogueReplicator.SendReplicate(newCardList);
            Log.Info(LogCat.Catalogue, $"Refreshed: {newCardList.Count} cards replicated to connected clients");
        }
        catch (Exception e)
        {
            Log.Error(LogCat.Catalogue, "Catalogue refresh failed, keeping the current catalogue", e);
        }
    }

    private async Task ServePlayerList(HttpListenerContext ctx)
    {
        var onlineIds = Databases.PlayerDatabase.GetAllPlayers().Select(p => p.PlayerId).ToHashSet();
        var allPlayers = await Databases.MasterServerDatabase.GetAllPlayersAsync();
        var players = allPlayers.Select(p => new
        {
            id = p.PlayerId,
            // As a string: a SteamID needs 57 bits, and JSON numbers land in a JS double,
            // which silently rounds anything past 2^53 to a different account.
            steam_id = p.SteamId.ToString(),
            nickname = p.Nickname,
            role = p.Role.ToString(),
            role_id = (int)p.Role,
            region = p.Region,
            online = onlineIds.Contains(p.PlayerId),
            // The ladder and the bans list are both built off this one response.
            rating_mean = p.Rating.Mean,
            rating_deviation = p.Rating.StandardDeviation,
            matchmaker_ban_end = p.MatchmakerBanEnd,
            graveyard_permanent = p.GraveyardPermanent,
            graveyard_leave_time = p.GraveyardLeaveTime
        });

        await WriteJson(ctx, new { players });
    }

    private async Task ServePlayerDetail(HttpListenerContext ctx, uint playerId)
    {
        var player = Databases.PlayerDatabase.GetPlayerDataNoWait(playerId);
        player ??= await Databases.MasterServerDatabase.GetPlayer(playerId);
        if (player == null)
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Player not found" });
            return;
        }

        var data = new
        {
            id = player.PlayerId,
            steam_id = player.SteamId.ToString(),
            nickname = player.Nickname,
            role = player.Role.ToString(),
            role_id = (int)player.Role,
            region = player.Region,
            online = Databases.PlayerDatabase.GetPlayerDataNoWait(playerId) != null,
            rating_mean = player.Rating.Mean,
            rating_deviation = player.Rating.StandardDeviation,
            league = player.League == null ? null : new
            {
                tier = player.League.Tier,
                division = player.League.Division,
                points = player.League.Points
            },
            progression_level = player.Progression.PlayerProgress?.Level ?? 0,
            tutorial_tokens = player.TutorialTokens,
            looking_for_friends = player.LookingForFriends,
            matchmaker_ban_end = player.MatchmakerBanEnd,
            graveyard_permanent = player.GraveyardPermanent,
            graveyard_leave_time = player.GraveyardLeaveTime,
            friends = player.Friends,
            friend_requests_incoming = player.RequestsFromFriends,
            friend_requests_outgoing = player.RequestsFromMe,
            notification_count = player.Notifications.Count,
            last_played_hero = player.LastPlayedHero.HasValue
                ? player.LastPlayedHero.Value.GetCard<BaseTypes.CardUnit>()?.Name?.Text
                    ?? player.LastPlayedHero.Value.GetCard<BaseTypes.CardUnit>()?.Id
                    ?? player.LastPlayedHero.Value.ToString()
                : null,
            badges = player.Badges.ToDictionary(
                b => b.Key.ToString(),
                b => b.Value.Select(key => key.GetCard<BaseTypes.CardBadge>()?.Name?.Text ?? key.GetCard<BaseTypes.CardBadge>()?.Id ?? key.ToString())),
            // Badge art, keyed by the same name `badges` lists, so the panel can look a
            // sprite up without the badge list changing shape. Titles have no icon.
            badge_icons = player.Badges.Values
                .SelectMany(list => list)
                .Select(key => key.GetCard<BaseTypes.CardBadge>())
                .Where(card => card is { Icon.Length: > 0 })
                .GroupBy(card => card!.Name?.Text ?? card.Id ?? string.Empty)
                .ToDictionary(g => g.Key, g => g.First()!.Icon),
            hero_stats = player.HeroStats.Select(h => new
            {
                hero = h.Hero.GetCard<BaseTypes.CardUnit>()?.Name?.Text ?? h.Hero.GetCard<BaseTypes.CardUnit>()?.Id ?? h.Hero.ToString(),
                wins = h.Wins,
                total_matches = h.TotalMatches
            }),
            match_history = player.MatchHistory
                .OrderByDescending(m => m.MatchEndTime)
                .Select(m => new
                {
                    hero = m.HeroKey.GetCard<BaseTypes.CardUnit>()?.Name?.Text ?? m.HeroKey.GetCard<BaseTypes.CardUnit>()?.Id ?? m.HeroKey.ToString(),
                    map = m.MapKey.GetCard<BaseTypes.CardMap>()?.Name?.Text ?? m.MapKey.GetCard<BaseTypes.CardMap>()?.Id ?? m.MapKey.ToString(),
                    game_mode = m.GameModeKey.GetCard<BaseTypes.CardGameMode>()?.Name ?? m.GameModeKey.GetCard<BaseTypes.CardGameMode>()?.Id ?? m.GameModeKey.ToString(),
                    end_time = m.MatchEndTime,
                    duration_seconds = m.MatchSeconds,
                    is_winner = m.IsWinner,
                    is_backfiller = m.IsBackfiller,
                    is_quit = m.IsQuit,
                    resources_earned = m.ResourcesEarned,
                    blocks_built = m.BlocksBuilt,
                    block_assist = m.BlockAssist,
                    destruction = m.Destruction,
                    objective_damage = m.ObjectiveDamage,
                    kill = m.Kill,
                    death = m.Death,
                    assist = m.Assist
                }),
            time_trial = new
            {
                completed_goal_count = player.TimeTrial.CompletedGoals?.Count ?? 0,
                best_result_count = player.TimeTrial.BestResultTime?.Count ?? 0,
                reset_time = player.TimeTrial.ResetTime
            },
            loadouts = player.HeroLoadouts.Values.Select(DescribeLoadout)
        };

        await WriteJson(ctx, data);
    }

    /// <summary>
    /// Records newer than the caller's cursor. The panel used to be sent the whole 10 000-line
    /// buffer every second and had to find the delta by matching a window of its own tail against
    /// the snapshot; a sequence number makes that guesswork unnecessary.
    ///
    /// Sequence numbers restart with the process, so the boot id goes out with every response —
    /// a caller whose boot id changed knows to drop its cursor and take the buffer from the top.
    /// Levels are never filtered here: the config decides what gets recorded, and the panel
    /// decides what gets shown, so raising the level cannot retroactively empty the history.
    /// </summary>
    private static async Task ServeLogs(HttpListenerContext ctx, string? since)
    {
        var cursor = long.TryParse(since, out var parsed) ? parsed : 0;
        var records = LogBuffer.Since(cursor);

        await WriteJson(ctx, new
        {
            boot = LogBuffer.Boot,
            next = LogBuffer.LastSeq,
            records = records.Select(r => new
            {
                seq = r.Seq,
                ts = r.Ts,
                lvl = LogNames.Of(r.Level),
                cat = LogNames.Of(r.Cat),
                msg = r.Msg,
                detail = r.Detail
            })
        });
    }

    private static async Task ServeCard(HttpListenerContext ctx, string query)
    {
        var card = uint.TryParse(query, out var hash)
            ? Databases.Catalogue.All.FirstOrDefault(c => c.Key.Hash == hash)
            : Databases.Catalogue.All.FirstOrDefault(c => string.Equals(c.Id, query, StringComparison.OrdinalIgnoreCase));

        if (card == null)
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Card not found" });
            return;
        }

        var json = JsonSerializer.Serialize(card, card.GetType(), JsonHelper.DefaultSerializerSettings);
        ctx.Response.ContentType = "application/json; charset=utf-8";
        var buf = System.Text.Encoding.UTF8.GetBytes(json);
        ctx.Response.ContentLength64 = buf.Length;
        await ctx.Response.OutputStream.WriteAsync(buf);
        ctx.Response.OutputStream.Close();
    }

    private static async Task ServeMaps(HttpListenerContext ctx)
    {
        var mapList = CatalogueHelper.MapList;
        var pools = new Dictionary<string, List<string>>
        {
            ["friendly"] = ResolveMapIds(mapList.Friendly),
            ["ranked"] = ResolveMapIds(mapList.Ranked),
            ["custom"] = ResolveMapIds(mapList.Custom)
        };
        var membership = pools.SelectMany(p => p.Value.Select(id => (id, p.Key)))
            .GroupBy(x => x.id).ToDictionary(g => g.Key, g => g.Select(x => x.Key).ToArray());
        var installed = Databases.MapDatabase.GetMapIds().Order(StringComparer.OrdinalIgnoreCase).ToList();
        var maps = installed.Select(id =>
        {
            var card = Catalogue.Key(id).GetCard<CardMap>();
            var data = Databases.MapDatabase.LoadMapData(Catalogue.Key(id));
            var unitIds = data?.Units.Select(unit => unit.UnitKey.GetCard<CardUnit>()?.Id ?? string.Empty).ToList() ?? [];
            return new
            {
                key = id,
                name = card?.Name?.Text ?? id,
                description = card?.Description?.Text ?? string.Empty,
                match = data?.Match.ToString(),
                size = data?.Size,
                cubes = unitIds.Where(unitId => unitId.StartsWith("unit_shield_line_", StringComparison.Ordinal))
                    .Distinct(StringComparer.Ordinal).Count(),
                bases = unitIds.Count(unitId => unitId.StartsWith("unit_base_", StringComparison.Ordinal)),
                image = card?.Image,
                large_image = card?.LargeImage,
                pools = membership.GetValueOrDefault(id) ?? []
            };
        });
        await WriteJson(ctx, new { maps, pools });
    }

    private static List<string> ResolveMapIds(IEnumerable<Key>? keys)
    {
        if (keys == null) return [];
        var installed = Databases.MapDatabase.GetMapIds();
        var names = installed.ToDictionary(Catalogue.Key, id => id, KeyEqualityComparer.Instance);
        return keys.Select(key => names.GetValueOrDefault(key) ?? $"#{key.Hash}").ToList();
    }

    private static async Task ServeMapDownload(HttpListenerContext ctx, string key)
    {
        var safe = Databases.MapDatabase.GetMapIds().FirstOrDefault(id => id == key);
        if (safe == null)
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Map not found" });
            return;
        }
        var path = Path.Combine(Databases.BaseFolderPath, "Maps", safe + ".bnlbin");
        ctx.Response.ContentType = "application/octet-stream";
        ctx.Response.AddHeader("Content-Disposition", $"attachment; filename=\"{safe}.bnlbin\"");
        var bytes = await File.ReadAllBytesAsync(path);
        ctx.Response.ContentLength64 = bytes.Length;
        await ctx.Response.OutputStream.WriteAsync(bytes);
        ctx.Response.OutputStream.Close();
    }

    private sealed class MapPoolUpdateRequest
    {
        public List<string>? Maps { get; set; }
    }

    private async Task HandleMapPoolUpdate(HttpListenerContext ctx, string pool)
    {
        if (pool is not ("friendly" or "ranked" or "custom"))
        {
            ctx.Response.StatusCode = 404;
            await WriteJson(ctx, new { error = "Map pool not found" });
            return;
        }
        var request = await JsonSerializer.DeserializeAsync<MapPoolUpdateRequest>(ctx.Request.InputStream, JsonOptions);
        var ids = request?.Maps;
        if (ids == null || ids.Count != ids.Distinct(StringComparer.Ordinal).Count())
        {
            ctx.Response.StatusCode = 400;
            await WriteJson(ctx, new { error = "Maps must be a duplicate-free list" });
            return;
        }
        var installed = Databases.MapDatabase.GetMapIds().ToHashSet(StringComparer.Ordinal);
        var invalid = ids.Where(id => !installed.Contains(id) || Catalogue.Key(id).GetCard<CardMap>() == null).ToList();
        if (invalid.Count > 0)
        {
            ctx.Response.StatusCode = 400;
            await WriteJson(ctx, new { error = $"Unknown or unplayable maps: {string.Join(", ", invalid)}" });
            return;
        }

        await _catalogueStore.UpdateMapPoolAsync(pool, ids);
        var cards = _catalogueStore.Load();
        _serverCatalogue.Replicate(cards);
        new Service.ServiceCatalogue(new ServerSender(_regionServer)).SendReplicate(cards);
        Log.Info(LogCat.Panel, $"Updated {pool} map pool ({ids.Count} maps) and replicated catalogue");
        await WriteJson(ctx, new { pool, maps = ids });
    }

    private static object DescribeLoadout(BaseTypes.LobbyLoadout loadout)
    {
        var heroCard = loadout.HeroKey.GetCard<BaseTypes.CardUnit>();
        var heroSkinCard = loadout.SkinKey.GetCard<BaseTypes.CardSkin>();

        return new
        {
            hero = heroCard?.Name?.Text ?? heroCard?.Id ?? loadout.HeroKey.ToString(),
            skin = heroSkinCard?.Name?.Text ?? heroSkinCard?.Id,
            // The portrait belongs to the skin, not the hero, so it follows the one
            // the player actually has equipped.
            hero_icon = heroSkinCard?.IconPortrait,
            devices = Enumerable.Range(1, 6).Select(slot =>
            {
                if (loadout.Devices == null || !loadout.Devices.TryGetValue(slot, out var deviceKey))
                    return new { slot, name = "(empty)", variant = (string?)null, icon = (string?)null };

                var deviceCard = deviceKey.GetCard<BaseTypes.CardDevice>();
                var groupCard = deviceCard?.GroupKey.GetCard<BaseTypes.CardDeviceGroup>();
                var baseDeviceKey = groupCard?.Devices?.FirstOrDefault();
                var baseDeviceCard = baseDeviceKey.HasValue ? baseDeviceKey.Value.GetCard<BaseTypes.CardDevice>() : null;

                var variantName = deviceCard?.Name?.Text ?? deviceCard?.Id ?? deviceKey.ToString();
                var className = baseDeviceCard?.Name?.Text ?? baseDeviceCard?.Id
                    ?? groupCard?.Name?.Text ?? groupCard?.Id
                    ?? variantName;

                var hasVariant = baseDeviceCard != null && baseDeviceCard.Key != deviceCard?.Key;

                // The equipped device's own icon, not the group's: a skinned variant is
                // drawn as the art the player sees in game.
                return new { slot, name = className, variant = hasVariant ? variantName : null, icon = deviceCard?.Icon };
            }),
            perks = new[]
            {
                BaseTypes.PerkSlotType.Defensive,
                BaseTypes.PerkSlotType.Offensive,
                BaseTypes.PerkSlotType.Hero
            }.Select(slotType =>
            {
                var equipped = loadout.Perks?
                    .Select(key => (key, perkCard: key.GetCard<BaseTypes.CardPerk>()))
                    .FirstOrDefault(p => p.perkCard?.SlotType == slotType);

                if (equipped == null || equipped.Value.perkCard == null)
                    return new { slot_type = slotType.ToString(), name = "(empty)", upside = (string?)null, downside = (string?)null, icon = (string?)null };

                var perkCard = equipped.Value.perkCard;
                var description = perkCard.Description?.Text;
                var parts = description?.Split(" / ", 2);

                return new
                {
                    slot_type = slotType.ToString(),
                    name = perkCard.Name?.Text ?? perkCard.Id ?? equipped.Value.key.ToString(),
                    upside = parts?.ElementAtOrDefault(0),
                    downside = parts?.ElementAtOrDefault(1),
                    icon = perkCard.Icon
                };
            })
        };
    }

    private async Task HandlePlayerUpdate(HttpListenerContext ctx, uint playerId)
    {
        try
        {
            using var reader = new StreamReader(ctx.Request.InputStream);
            var body = await reader.ReadToEndAsync();
            using var doc = JsonDocument.Parse(body);
            var root = doc.RootElement;

            var livePlayer = Databases.PlayerDatabase.GetPlayerDataNoWait(playerId);
            var dbPlayer = livePlayer ?? await Databases.MasterServerDatabase.GetPlayer(playerId);
            if (dbPlayer == null)
            {
                ctx.Response.StatusCode = 404;
                await WriteJson(ctx, new { error = "Player not found" });
                return;
            }

            var updated = dbPlayer;

            if (root.TryGetProperty("nickname", out var nicknameProp))
            {
                updated.Nickname = nicknameProp.GetString() ?? updated.Nickname;
                if (livePlayer != null)
                    Databases.PlayerDatabase.SetPlayerName(playerId, updated.Nickname);
            }

            if (root.TryGetProperty("role_id", out var roleProp))
                updated.Role = (BaseTypes.PlayerRole)roleProp.GetInt32();

            if (root.TryGetProperty("region", out var regionProp))
                updated.Region = regionProp.GetString();

            if (root.TryGetProperty("rating_mean", out var meanProp) || root.TryGetProperty("rating_deviation", out _))
            {
                var mean = root.TryGetProperty("rating_mean", out var m) ? m.GetDouble() : updated.Rating.Mean;
                var dev = root.TryGetProperty("rating_deviation", out var d) ? d.GetDouble() : updated.Rating.StandardDeviation;
                updated.Rating = new Moserware.Skills.Rating(mean, dev);
            }

            // No league_tier/league_division/league_points here: a rank is a position on the
            // ladder now, so edit the rating and the tier follows.

            if (root.TryGetProperty("tutorial_tokens", out var tokensProp))
                updated.TutorialTokens = tokensProp.GetInt32();

            if (root.TryGetProperty("looking_for_friends", out var lffProp))
                updated.LookingForFriends = lffProp.GetBoolean();

            if (root.TryGetProperty("matchmaker_ban_end", out var banProp))
                updated.MatchmakerBanEnd = banProp.ValueKind == JsonValueKind.Null ? null : banProp.GetUInt64();

            if (root.TryGetProperty("graveyard_permanent", out var gpProp))
                updated.GraveyardPermanent = gpProp.ValueKind == JsonValueKind.Null ? null : gpProp.GetBoolean();

            if (root.TryGetProperty("graveyard_leave_time", out var gltProp))
                updated.GraveyardLeaveTime = gltProp.ValueKind == JsonValueKind.Null ? null : gltProp.GetUInt64();

            var saved = await Databases.MasterServerDatabase.UpdatePlayerAsync(playerId, updated);
            if (!saved)
            {
                ctx.Response.StatusCode = 500;
                await WriteJson(ctx, new { error = "Failed to persist changes to database" });
                return;
            }

            await WriteJson(ctx, new { message = "Player updated" });
        }
        catch (Exception ex)
        {
            ctx.Response.StatusCode = 500;
            await WriteJson(ctx, new { error = ex.Message });
        }
    }

    private static async Task WriteJson(HttpListenerContext ctx, object data)
    {
        ctx.Response.ContentType = "application/json; charset=utf-8";
        var buf = JsonSerializer.SerializeToUtf8Bytes(data, JsonOptions);
        ctx.Response.ContentLength64 = buf.Length;
        await ctx.Response.OutputStream.WriteAsync(buf);
        ctx.Response.OutputStream.Close();
    }
}
