namespace BNLReloadedServer.BaseTypes;

public enum CardCategory
{
    Block = 1,
    Map = 2,
    MapData = 3,
    Match = 4,
    GameMode = 5,
    GlobalLogic = 6,
    ChatLogic = 7,
    SettingsLogic = 8,
    MovementLogic = 9,
    LeagueLogic = 10,
    VibrationLogic = 11,
    ShopLogic = 12,
    RewardsLogic = 13,
    MapLogic = 14,
    MapList = 15,
    Gear = 16,
    Device = 17,
    DeviceGroup = 18,
    Unit = 19,
    Projectile = 20,
    Effect = 21,
    DamageSource = 22,
    Material = 23,
    Impact = 24,
    HeroClass = 25,
    Perk = 26,
    Ability = 27,
    MatchMedal = 28,
    Badge = 29,
    Skin = 30,
    Achievement = 31,
    Challenge = 32,
    Notification = 33,
    Booster = 34,
    ShopItem = 35,
    SteamShopItem = 36,
    SteamDlcItem = 37,
    Reward = 38,
    Rubble = 39,
    LootCrate = 40,
    Strings = 41
}
