namespace BNLReloadedServer.BaseTypes;

public enum InstEffectType
{
    Damage = 1,
    SplashDamage = 2,
    Heal = 3,
    Supply = 4,
    AddAmmo = 5,
    AddAmmoPercent = 6,
    DrainAmmo = 7,
    DrainMagazineAmmo = 8,
    AddResource = 9,
    UnitSpawn = 10,
    BlocksSpawn = 11,
    BuildDevice = 12,
    Bunch = 13,
    AllUnitsBunch = 14,
    CasterBunch = 15,
    HealBlocks = 16,
    DamageBlocks = 17,
    Teleport = 18,
    TeleportTo = 19,
    FireMortars = 20,
    Knockback = 21,
    Purge = 22,
    InstReload = 23,
    Kill = 24,
    ChargeTesla = 25,
    AllPlayersPersistent = 26,
    ResourceAll = 27,
    ZoneEffect = 28,
    Slip = 29,
    ReplaceBlocks = 30
}
