#!/usr/bin/env python3
"""Copy the panel's loadout/profile art out of the client project.

    python3 sprites.py            # extract into ../BNLReloadedServer/ControlPanel/assets
    python3 sprites.py --check    # report only, write nothing

The panel draws four kinds of sprite, and the server now names each one by its CDB
`icon` field rather than by the card's display name — see `DescribeLoadout` and the
`badge_icons` map in ControlPanelServer.cs.  Files are written under the icon name, so
the client's `_small` / `_50` suffixes disappear here and the panel never has to know
which variant a sprite happened to ship as:

    devices/<icon>.png     device.icon              60px
    perks/<icon>.png       perk.icon                60px
    portraits/<icon>.png   skin.icon_portrait       60px   (client: <icon>_small)
    badges/<icon>.png      badge.icon               50px   (client: <icon>_50)

The icon *names* are read from the CDB export, which is a snapshot — the live
`Cache/cdb` can name an icon this file has never heard of.  That is exactly why the
script also writes `sprites.js`: the panel looks a sprite up in that manifest and draws
an empty tile when it misses, so drift costs a missing icon rather than a broken image.
Rerun this after a catalogue update.

Border sprites stay at their native size: a border is a 110px corner piece the panel
draws four times, rotated, and scaling it down softens the joins.
"""

import glob
import json
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CLIENT = '/home/danny/Projects/BlockNLoad/Assets'
CDB = os.path.join(REPO, 'Cache', 'cdb2025_export.json')
OUT = os.path.join(REPO, 'BNLReloadedServer', 'ControlPanel', 'assets')
MANIFEST = os.path.join(REPO, 'BNLReloadedServer', 'ControlPanel', 'sprites.js')

# folder, size, and the client filename variants to look for, best first
# Sizes are 2x the CSS box the panel draws them in (30px icons, 50px badge slots).
KINDS = {
    'devices':   (60,  ['{0}']),
    'perks':     (60,  ['{0}']),
    'portraits': (60,  ['{0}_small', '{0}']),
    'badges':    (50,  ['{0}_50', '{0}']),
}
# Borders are badges by card, but they are drawn as a frame rather than an icon.
BORDER = ('borders', 110, ['{0}'])


def wanted():
    """icon names the catalogue asks for, by folder."""
    cards = json.load(open(CDB))
    out = {k: set() for k in list(KINDS) + ['borders']}
    for c in cards:
        cat, icon = c.get('category'), c.get('icon')
        if cat == 'device' and icon:
            out['devices'].add(icon)
        elif cat == 'perk' and icon:
            out['perks'].add(icon)
        elif cat == 'badge' and icon:
            out['borders' if 'border' in icon else 'badges'].add(icon)
        elif cat == 'skin' and c.get('icon_portrait'):
            out['portraits'].add(c['icon_portrait'])
    return out


def client_index():
    index = {}
    for p in glob.glob(os.path.join(CLIENT, '**', '*.png'), recursive=True):
        index.setdefault(os.path.basename(p)[:-4], p)
    return index


def main():
    check = '--check' in sys.argv
    if not os.path.isdir(CLIENT):
        sys.exit(f'{CLIENT}: not found. The sprites come from the client project, which '
                 'lives outside this repo — point CLIENT at its Assets folder.')

    index = client_index()
    specs = dict(KINDS)
    specs[BORDER[0]] = (BORDER[1], BORDER[2])

    shipped, missing, total = {}, {}, 0
    for folder, names in wanted().items():
        size, patterns = specs[folder]
        dest = os.path.join(OUT, folder)
        if not check:
            os.makedirs(dest, exist_ok=True)
        got, gone = [], []
        for name in sorted(names):
            src = next((index[p.format(name)] for p in patterns if p.format(name) in index), None)
            if src is None:
                gone.append(name)
                continue
            got.append(name)
            if check:
                continue
            im = Image.open(src).convert('RGBA')
            if max(im.size) > size:
                im.thumbnail((size, size), Image.LANCZOS)
            im.save(os.path.join(dest, name + '.png'), optimize=True)
            total += os.path.getsize(os.path.join(dest, name + '.png'))
        shipped[folder], missing[folder] = got, gone
        print(f'{folder:10} {len(got):4} shipped, {len(gone):3} with no client art')
        if gone:
            print(f'{"":10} missing: ' + ', '.join(gone[:6]) + (' …' if len(gone) > 6 else ''))

    if check:
        return
    print(f'{total // 1024} KB written to {OUT}')

    with open(MANIFEST, 'w') as f:
        f.write('/* Generated by web-rework-prototype/sprites.py — do not edit.\n'
                '   Every sprite this panel ships, by the CDB `icon` name the API sends.\n'
                '   A name that is not here draws an empty tile, never a broken image. */\n')
        f.write('const SPRITES = {\n')
        for folder in sorted(shipped):
            f.write('  %s: new Set(%s),\n' % (folder, json.dumps(sorted(shipped[folder]))))
        f.write('};\n')
    print('manifest:', MANIFEST)


if __name__ == '__main__':
    main()
